from pyprone.entities import PrText

text = PrText(f"text{1:04}")
text.append("text appended")
text.append("Hi yo Hi yo Hi yo")
text.log(text.text)
text.append("Hi yo Hi yo Hi yo")
text.log(text.text)
text.append("Hi yo Hi yo Hi yo")
text.log(text.text)
text.append("Hi yo Hi yo Hi yo")
text.log(text.text)
text.append("Hi yo Hi yo Hi yo")
text.log(text.text)
text.append("Hi yo Hi yo Hi yo")
text.log(text.text)
text.append("Hi yo Hi yo Hi yo")
text.log(text.text)
text.append("Hi yo Hi yo Hi yo")
text.log(text.text)
text.append("Hi yo Hi yo Hi yo")
text.log(text.text)
text.append("Hi yo Hi yo Hi yo")
text.log(text.text)
text.append("Hi yo Hi yo Hi yo")
text.log(text.text)
